services:
  - type: web
    name: ficha-darkness
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run backend
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATA_DIR
        value: /opt/render/project/src/storage
    disk:
      name: fichas
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
